#!/bin/bash
#
# repo_server	This shell script takes care of starting and stopping
#		repo_server (dynamic ubuntu repo server).
#
# chkconfig: - 58 74
# description: repo_server is a dynamic ubuntu repository server.

### BEGIN INIT INFO
# Provides: repo_server
# Required-Start: $network $local_fs $remote_fs
# Required-Stop: $network $local_fs $remote_fs
# Should-Start: $syslog $named
# Should-Stop: $syslog $named
# Short-Description: start and stop repo_server
# Description: repo_server is a dynamic Ubuntu repository server.
### END INIT INFO

# Source function library.
. /etc/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

prog=repo_server
lockfile=/var/lock/subsys/$prog

start() {
	[ "$EUID" != "0" ] && exit 4
	[ "$NETWORKING" = "no" ] && exit 1
	[ -x /usr/bin/repo_server ] || exit 5
	[ -f /etc/sysconfig/repo_server ] && . /etc/sysconfig/repo_server

        # Start daemons.
        echo -n $"Starting $prog: "
        daemon --user repo $prog $OPTIONS 2>/var/repo/repo.log &
	RETVAL=$?
        echo
	[ $RETVAL -eq 0 ] && touch $lockfile
	return $RETVAL
}

stop() {
	[ "$EUID" != "0" ] && exit 4
        echo -n $"Shutting down $prog: "
	killproc $prog
	RETVAL=$?
        echo
	[ $RETVAL -eq 0 ] && rm -f $lockfile
	return $RETVAL
}

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  status)
	status $prog
	;;
  restart|force-reload)
	stop
	start
	;;
  try-restart|condrestart)
	if status $prog > /dev/null; then
	    stop
	    start
	fi
	;;
  reload)
	exit 3
	;;
  *)
	echo $"Usage: $0 {start|stop|status|restart|try-restart|force-reload}"
	exit 2
esac
