#!/bin/bash

set -e

if [ -z "$1" ]; then
    echo "usage: $0 <datadir> [keyring]"
    exit 1
fi

keyring="keyring"
if [ ! -z "$2" ]; then
    keyring="$2"
fi

dir="$(dirname "$0")"
dir="$(cd "${dir}"; pwd)"

base="$(dirname "${dir}")"
datadir="$1"
version="$(${dir}/version)"
name="repo_server"
package="repo-server"
user="reposerver"
group="reposerver"

sed_script="s|@@datadir@@|${datadir}|g;s|@@version@@|${version}|g;s|@@name@@|${name}|g;s|@@package@@|${package}|g;s|@@user@@|${user}|g;s|@@group@@|${group}|g"

echo "Build ${name} DEB: v${version}"
echo

echo "Run some checks ..."
dpkgdeb="$(which dpkg-deb 2>/dev/null)"
if [ -z "${dpkgdeb}" ]; then
    echo "  unable to find dpkg-deb!"
    exit 1
fi
if [ ! -f "${base}/${name}" ]; then
    echo "  ${name} has not been built!"
    exit 1
fi
if [ ! -f "${base}/config.yml" ]; then
    echo "  ${name} has not been configured!"
    exit 1
fi
if [ ! -f "${base}/${keyring}" ]; then
    echo "  keyring (${keyring}) does not exist!"
    exit 1
fi

echo "Create build tree ..."
scratch="${dir}/scratch"
mkdir -p "${scratch}"
mkdir -p "${scratch}/DEBIAN"
mkdir -p "${scratch}/usr/bin"
mkdir -p "${scratch}/lib/systemd/system/"
mkdir -p "${scratch}/usr/share/doc/${package}"
mkdir -p "${scratch}/usr/share/lintian/overrides"
mkdir -p "${scratch}/${datadir}"

echo "Create control file ..."
sed -e "${sed_script}" "${dir}/template.control" > "${scratch}/DEBIAN/control"

echo "Create package scripts ..."
sed -e "${sed_script}" "${dir}/template.preinst" > "${scratch}/DEBIAN/preinst"
sed -e "${sed_script}" "${dir}/template.prerm" > "${scratch}/DEBIAN/prerm"
sed -e "${sed_script}" "${dir}/template.postinst" > "${scratch}/DEBIAN/postinst"
sed -e "${sed_script}" "${dir}/template.postrm" > "${scratch}/DEBIAN/postrm"

echo "Collate files ..."

cp "${base}/${name}" "${scratch}/usr/bin/"
cp "${base}/config.yml" "${scratch}/${datadir}/"
cp "${base}/${keyring}" "${scratch}/${datadir}/"
sed -e "${sed_script}" "${dir}/template.systemd" > "${scratch}/lib/systemd/system/${package}.service"

cp "${base}/LICENSE" "${scratch}/usr/share/doc/${package}/copyright"
cp "${base}/README.md" "${scratch}/usr/share/doc/${package}/"
cp "${base}/example_config.yml" "${scratch}/usr/share/doc/${package}/"

cp "${dir}/lintian" "${scratch}/usr/share/lintian/overrides/${package}"

echo "Fix permissions ..."
find "${scratch}" -type f -exec chmod 644 {} \;
find "${scratch}" -type d -exec chmod 755 {} \;
find "${scratch}/usr/bin" -type f -exec chmod 755 {} \;
find "${scratch}/DEBIAN" -name "pre*" -exec chmod 755 {} \;
find "${scratch}/DEBIAN" -name "post*" -exec chmod 755 {} \;

echo "Run dpkg-deb ..."
fakeroot dpkg-deb --build "${scratch}" "${dir}"

echo "Remove build tree ..."
rm -r "${scratch}"
